name: ðŸš€ GenDiff Check

on: [push, pull_request]

jobs:
  build-and-test:
    name: ðŸ›  Build & ðŸ” Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: ðŸ”‘ Checkout Code
    
    - name: ðŸŒ Use Node.js 21
      uses: actions/setup-node@v1
      with:
        node-version: '21'
        
    - name: ðŸ“¦ Install Dependencies
      run: make install
      
    - name: ðŸ”Ž Lint Code
      run: make lint
      
    - name: ðŸ§ª Run Tests
      run: make test

    - name: ðŸ“Š Send Test Coverage to CodeClimate
          env:
            CODECLIMATE_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          run: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
            npm test -- --coverage
            ./cc-test-reporter after-build --exit-code ${{ job.status }} -t lcov
